name: VillagerTradeLimiter
author: PretzelJohn
main: com.pretzel.dev.villagertradelimiter.VillagerTradeLimiter
version: 1.6.3
api-version: 1.14
folia-supported: true

commands:
  villagertradelimiter:
    description: Base command for VTL
    usage: /<command>
    permission: villagertradelimiter.use
    aliases: vtl
permissions:
  villagertradelimiter.*:
    description: Gives access to all commands.
    children:
      villagertradelimiter.use: true
      villagertradelimiter.reload: true
      villagertradelimiter.see: true
      villagertradelimiter.invsee: true
    default: op
  villagertradelimiter.use:
    description: Allows players to use VillagerTradeLimiter.
    default: op
  villagertradelimiter.reload:
    description: Allows players to reload config.yml.
    default: op
  villagertradelimiter.see:
    description: Allows players to see the trades for another player
    default: op
  villagertradelimiter.invsee:
    description: Allows players to see inventory of a villager
    default: op